### ISSUE TITLE
can‘t install PyMesh third party mmg v5.4.3

### ISSUE THREAD

**Issue by maluonei** [78ij/NU-NeRF#1]
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/mmg2d.dir/build.make:99：bin/mmg2d_O3] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:310：CMakeFiles/mmg2d.dir/all] 错误 2
gmake: *** [Makefile:156：all] 错误 2
Traceback (most recent call last):
  File "third_party/build.py", line 82, in <module>
    main();
  File "third_party/build.py", line 79, in main
    build(args.package, args.cleanup);
  File "third_party/build.py", line 75, in build
    build_generic(package, cleanup=cleanup);
  File "third_party/build.py", line 47, in build_generic
    subprocess.check_call(cmd.split());
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/disk/ydw/NU-NeRF/PyMesh/third_party/../third_party/build/mmg']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "setup.py", line 200, in <module>
    distclass=BinaryDistribution,
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 102, in run
    self.build_third_party()
  File "setup.py", line 68, in build_third_party
    check_call(c.split())
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['third_party/build.py', 'mmg']' returned non-zero exit status 1.

**Comment by 78ij** [comment]
Hi,
It seems the logs you pasted here is not complete (only the make and setup.py call stack is here). From the log, the linking has an error (ld status -1). It would be beneficial for locating the error if that part of the message is present (it may be printed prior to this message in the terminal).

**Comment by maluonei** [comment]
sorry，I recompile mmg and the output is here:
/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/dist.py:773: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  % (opt, underscore_opt)
== CMake setup ==
== CMake setup (DONE) ==

== Setting paths ==
== Setting paths (DONE) ==

== Generate version files ==
== Generate version files (DONE) ==

== Detect external libraries ==
== Detect external libraries (DONE) ==

== Generating build files ==
Configuring libCGAL
libCGAL is configured
Configuring libCGAL_Core
libCGAL_Core is configured
== Generating build files (DONE) ==

CMake Warning at Installation/cmake/modules/CGAL_enable_end_of_configuration_hook.cmake:99 (message):
  =======================================================================

  CGAL performance notice:

  The variable CMAKE_BUILD_TYPE is set to "".  For performance reasons, you
  should set CMAKE_BUILD_TYPE to "Release".

  Set CGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE to TRUE if you want to disable
  this warning.

  =======================================================================
Call Stack (most recent call first):
  CMakeLists.txt:9223372036854775807 (CGAL_run_at_the_end_of_configuration)


CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at CMakeLists.txt:64 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


--- Running combined CXX flags test, flags: -Wno-deprecated-declarations
--- Passed combined CXX flags test
CMake Deprecation Warning at CMakeLists.txt:23 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SCOTCH)
  does not match the name of the calling package (Scotch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindScotch.cmake:364 (find_package_handle_standard_args)
  CMakeLists.txt:220 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at CMakeLists.txt:223 (MESSAGE):
  Scotch library not found:Using scotch reduce the execution time of mmg3d
  (see https://gforge.inria.fr/frs/?group_id=248 to download it).If you have
  already installed Scotch and want to use it, please set the CMake variable
  or environment variable SCOTCH_DIR to your scotch directory.


/usr/bin/ld: lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x30): multiple definition of `MMG5_compute_meanMetricAtMarkedPoints'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x0): first defined here
/usr/bin/ld: lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x38): multiple definition of `MMG5_grad2metreq_ani'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x8): first defined here
/usr/bin/ld: lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x40): multiple definition of `MMG5_grad2met_ani'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x10): first defined here
/usr/bin/ld: lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x48): multiple definition of `MMG5_indPt'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x18): first defined here
/usr/bin/ld: lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x50): multiple definition of `MMG5_indElt'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x20): first defined here
/usr/bin/ld: lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x58): multiple definition of `MMG5_lenSurfEdg'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x28): first defined here
/usr/bin/ld: lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x60): multiple definition of `MMG5_bezierCP'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x30): first defined here
/usr/bin/ld: lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x68): multiple definition of `MMG5_chkmsh'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x38): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x30): multiple definition of `MMG5_compute_meanMetricAtMarkedPoints'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x0): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x0): multiple definition of `MMG2D_gradsiz'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x0): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x8): multiple definition of `MMG2D_caltri'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x8): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x10): multiple definition of `MMG2D_gradsizreq'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x10): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x18): multiple definition of `MMG2D_lencurv'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x18): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x20): multiple definition of `MMG2D_intmet'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x20): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x28): multiple definition of `MMG2D_defsiz'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x28): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x38): multiple definition of `MMG5_grad2metreq_ani'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x8): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x40): multiple definition of `MMG5_grad2met_ani'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x10): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x48): multiple definition of `MMG5_indPt'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x18): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x50): multiple definition of `MMG5_indElt'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x20): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x58): multiple definition of `MMG5_lenSurfEdg'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x28): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x60): multiple definition of `MMG5_bezierCP'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x30): first defined here
/usr/bin/ld: lib/libmmg2d.a(isosiz_2d.c.o):(.bss+0x68): multiple definition of `MMG5_chkmsh'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x38): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x68): multiple definition of `MMG5_chkmsh'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x38): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x40): multiple definition of `MMG5_grad2met_ani'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x10): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x38): multiple definition of `MMG5_grad2metreq_ani'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x8): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x0): multiple definition of `MMG2D_gradsiz'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x0): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x8): multiple definition of `MMG2D_caltri'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x8): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x10): multiple definition of `MMG2D_gradsizreq'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x10): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x18): multiple definition of `MMG2D_lencurv'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x18): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x20): multiple definition of `MMG2D_intmet'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x20): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x28): multiple definition of `MMG2D_defsiz'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x28): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x30): multiple definition of `MMG5_compute_meanMetricAtMarkedPoints'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x0): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x48): multiple definition of `MMG5_indPt'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x18): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x50): multiple definition of `MMG5_indElt'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x20): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x58): multiple definition of `MMG5_lenSurfEdg'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x28): first defined here
/usr/bin/ld: lib/libmmg2d.a(libmmg2d.c.o):(.bss+0x60): multiple definition of `MMG5_bezierCP'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x30): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x68): multiple definition of `MMG5_chkmsh'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x38): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x40): multiple definition of `MMG5_grad2met_ani'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x10): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x38): multiple definition of `MMG5_grad2metreq_ani'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x8): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x0): multiple definition of `MMG2D_gradsiz'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x0): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x8): multiple definition of `MMG2D_caltri'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x8): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x10): multiple definition of `MMG2D_gradsizreq'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x10): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x18): multiple definition of `MMG2D_lencurv'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x18): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x20): multiple definition of `MMG2D_intmet'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x20): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x28): multiple definition of `MMG2D_defsiz'; lib/libmmg2d.a(anisosiz_2d.c.o):(.bss+0x28): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x30): multiple definition of `MMG5_compute_meanMetricAtMarkedPoints'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x0): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x48): multiple definition of `MMG5_indPt'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x18): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x50): multiple definition of `MMG5_indElt'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x20): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x58): multiple definition of `MMG5_lenSurfEdg'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x28): first defined here
/usr/bin/ld: lib/libmmg2d.a(variadic_2d.c.o):(.bss+0x60): multiple definition of `MMG5_bezierCP'; lib/libmmg2d.a(mmgexterns.c.o):(.bss+0x30): first defined here
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/mmg2d.dir/build.make:99：bin/mmg2d_O3] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:310：CMakeFiles/mmg2d.dir/all] 错误 2
gmake: *** [Makefile:156：all] 错误 2
Traceback (most recent call last):
  File "third_party/build.py", line 82, in <module>
    main();
  File "third_party/build.py", line 79, in main
    build(args.package, args.cleanup);
  File "third_party/build.py", line 75, in build
    build_generic(package, cleanup=cleanup);
  File "third_party/build.py", line 47, in build_generic
    subprocess.check_call(cmd.split());
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/disk/ydw/NU-NeRF/PyMesh/third_party/../third_party/build/mmg']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "setup.py", line 200, in <module>
    distclass=BinaryDistribution,
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 102, in run
    self.build_third_party()
  File "setup.py", line 68, in build_third_party
    check_call(c.split())
  File "/home/h3c/anaconda3/envs/ydw_gsdf/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['third_party/build.py', 'mmg']' returned non-zero exit status 1.
[log.txt](https://github.com/user-attachments/files/17900078/log.txt)

**Comment by maluonei** [comment]
could you please tell me the cuda and pytorch version you used?

**Comment by 78ij** [comment]
My cuda version is 12.4, and torch version is 2.5.0.

I see someone with a similar problem with you, can you try the solution posted here?
https://github.com/PyMesh/PyMesh/issues/255
i.e.  add the following line to ```PyMesh/third_party/mmg/CMakelists.txt```
```
SET(CMAKE_C_FLAGS " -fcommon ${CMAKE_C_FLAGS}")

```
Also, I built this with gcc-9 and g++-9, there is also probabilities that you are using newer versions of gcc and g++ (e.g. version 13), which is generating this problem.

**Comment by maluonei** [comment]
thanks, adding SET(CMAKE_C_FLAGS " -fcommon ${CMAKE_C_FLAGS}") solves the problem

**Comment by 78ij** [comment]
Good to see the problem solved. I am closing this issue as completed.
