### ISSUE TITLE
OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found

### ISSUE THREAD

**Issue by yhccc** [78ij/NU-NeRF#2]
When I run the code "CUDA_VISIBLE_DEVICES=1 python run_training.py --cfg configs/shape/nerf/glassice.yaml", I encountered the following error: 
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
Exception ignored in: 'optix.common.optix_init'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
Exception ignored in: 'optix.common.optix_init'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
Exception ignored in: 'optix.common.optix_init'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
Exception ignored in: 'optix.common.optix_init'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
Exception ignored in: 'optix.common.optix_init'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
Exception ignored in: 'optix.common.optix_init'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
Exception ignored in: 'optix.common.optix_init'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
Exception ignored in: 'optix.common.optix_init'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found
Exception ignored in: 'optix.common.optix_init'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
RuntimeError: OPTIX_ERROR_LIBRARY_NOT_FOUND: Library not found

$ echo $OPTIX_EMBED_HEADERS
1
$ echo $CUDA_PATH
/usr/local/cuda-11.8
$ echo $OPTIX_PATH
/usr/local/NVIDIA-OptiX-SDK-7.6.0-linux64-x86_64/

Do you have any idea for solving this problem?

**Comment by 78ij** [comment]
Hi,
Sadly i did not encounter this type of problem. But as far as I know, it may be a issue of the driver. Optix 7.6.0 needs a NVIDIA Driver version 522.25 or newer, you may try to update or re-install the driver to get this solved.(because a large portion of optix libraries comes with NVIDIA driver nowadays)
To confirm whether you have the optix library, you can check  /usr/lib/x86_64-linux-gnu/libnvoptix.so.1, if it not exists, then maybe there is something wrong with the driver.

**Comment by yhccc** [comment]
> Hi, Sadly i did not encounter this type of problem. But as far as I know, it may be a issue of the driver. Optix 7.6.0 needs a NVIDIA Driver version 522.25 or newer, you may try to update or re-install the driver to get this solved.(because a large portion of optix libraries comes with NVIDIA driver nowadays) To confirm whether you have the optix library, you can check /usr/lib/x86_64-linux-gnu/libnvoptix.so.1, if it not exists, then maybe there is something wrong with the driver.

Thanks for your reply.
I deploy the code in the docker. The Driver version is 550.120. The docker image is nvcr.io/nvidia/cuda:11.8.0-devel-ubuntu22.04        
![image](https://github.com/user-attachments/assets/15e5fe54-f1d8-4c69-a324-8959fe07b13b)
   
I check the path "/usr/lib/x86_64-linux-gnu".  The file "libnvoptix.so.1" doesn't exist.
I will fix the driver. The code of the Stage 1 runs correctly. The results are as follows:
![image](https://github.com/user-attachments/assets/d59cd649-40f5-4598-a2fe-f1b96fb1760b)
![image](https://github.com/user-attachments/assets/0df85570-c0a0-458e-aa11-afbf6f931d75)

But, the program "python render_mask.py --cfg configs/shape/nerf/glassice.yaml --mesh_path xxxxx" run with segmentation fault.
Abnormal program termination: received signal 11 (Segmentation fault)
![image](https://github.com/user-attachments/assets/105c805c-290e-4fe0-ad11-2acb8323a599)

**Comment by 78ij** [comment]
It seems the same error as your original issue..? 
I think the error may be relevant to the docker, since there are some similar issues on NVIDIA forums(some of them are old, but still relevant):
https://forums.developer.nvidia.com/t/optix-6-0-0-inside-nvidia-docker/72968/12
https://github.com/NVIDIA/nvidia-docker/issues/990
https://github.com/NVIDIA/nvidia-container-toolkit/issues/187
I think you may considering using the official docker provided by NVIDIA, or try the method suggested by them.

**Comment by yhccc** [comment]
> It seems the same error as your original issue..? I think the error may be relevant to the docker, since there are some similar issues on NVIDIA forums(some of them are old, but still relevant): https://forums.developer.nvidia.com/t/optix-6-0-0-inside-nvidia-docker/72968/12 [NVIDIA/nvidia-docker#990](https://github.com/NVIDIA/nvidia-docker/issues/990) [NVIDIA/nvidia-container-toolkit#187](https://github.com/NVIDIA/nvidia-container-toolkit/issues/187) I think you may considering using the official docker provided by NVIDIA, or try the method suggested by them.

Thanks a lot. I think you are right.
I deployed the code on the host machine and no more errors were reported.
I check the path "/usr/lib/x86_64-linux-gnu". The file "libnvoptix.so.1" exists.
I will close this issue.
